
tasks:
  - name: Install development tools
    command: brew install lua busted stylua deno

vscode:
  extensions:
    - sumneko.lua
    - denoland.vscode-deno

ports:
  - port: 8000
    visibility: private

image:
  file: .gitpod.Dockerfile
