
tasks:
  - name: Install development tools
    command: brew install lua busted stylua deno
  - name: Start web app
    command: make serve

vscode:
  extensions:
    - sumneko.lua

ports:
  - port: 8000
    visibility: private