
tasks:
  - name: Launch server
    command: make serve

vscode:
  extensions:
    - sumneko.lua
    - denoland.vscode-deno

ports:
  - port: 8000
    visibility: private

image:
  file: .gitpod.Dockerfile
